language: java
jdk:
  - oraclejdk8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: "mvn deploy -DskipTests -Prelease -Dgpg.skip=true --settings src/travis/settings.xml -pl :framework,:framework-test,:rise-es -am" 

