language: java
jdk:
  - oraclejdk8
script: "mvn deploy -DskipTests -Prelease -Dgpg.skip=true -Dmaven.javadoc.skip=true --settings src/travis/settings.xml -pl :framework,:framework-test,:rise-es -am" 

